# Generated by Django 3.2.23 on 2024-02-12 12:41

import datetime
from django.db import migrations, models
# from django.utils.timezone import utc
from datetime import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 13, 41, 45, 351935, tzinfo=timezone.utc)),
        ),
    ]
