# Generated by Django 5.0.2 on 2024-03-12 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 16, 0, 30, 262418, tzinfo=datetime.timezone.utc)),
        ),
    ]
