# Generated by Django 5.0.2 on 2024-03-29 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_barber_bio_barber_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='salons',
            field=models.ManyToManyField(blank=True, null=True, related_name='barbers', to='reserve.salon'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='services_offered',
            field=models.ManyToManyField(blank=True, null=True, to='reserve.service'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 1, 12, 38, 273832, tzinfo=datetime.timezone.utc)),
        ),
    ]
