# Generated by Django 5.0.2 on 2024-03-29 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_alter_barber_salons_alter_barber_services_offered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 1, 50, 59, 983466, tzinfo=datetime.timezone.utc)),
        ),
    ]
