# Generated by Django 3.2.23 on 2024-04-04 21:47

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 4, 22, 47, 19, 491207, tzinfo=utc)),
        ),
    ]
