# Generated by Django 3.2.23 on 2024-04-04 22:08

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0008_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 4, 23, 8, 4, 820369, tzinfo=utc)),
        ),
    ]
