# Generated by Django 5.0.4 on 2024-04-21 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='location',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 9, 29, 26, 844935, tzinfo=datetime.timezone.utc)),
        ),
    ]
