# Generated by Django 3.2.23 on 2024-04-21 10:19

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_barber_location_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('landing_image', models.ImageField(upload_to='')),
                ('gif_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 11, 19, 58, 500406, tzinfo=utc)),
        ),
    ]
