# Generated by Django 3.2.23 on 2024-04-21 10:20

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_auto_20240421_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 11, 20, 32, 341279, tzinfo=timezone.utc)),
        ),
    ]
