# Generated by Django 3.2.23 on 2024-04-21 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0011_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 11, 20, 54, 752447, tzinfo=utc)),
        ),
    ]
