# Generated by Django 3.2.23 on 2024-04-21 10:38

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0013_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Landing',
            new_name='LandingUP',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 11, 38, 28, 350086, tzinfo=utc)),
        ),
    ]
