# Generated by Django 3.2.23 on 2024-04-21 10:48

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0014_auto_20240421_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('landing_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LandingMid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('landing_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 11, 48, 4, 341897, tzinfo=utc)),
        ),
    ]
