# Generated by Django 5.0.4 on 2024-04-24 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0015_auto_20240421_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 10, 18, 54, 429850, tzinfo=datetime.timezone.utc)),
        ),
    ]
