# Generated by Django 5.0.4 on 2024-04-24 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0016_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='barber',
            new_name='recipient_barber',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='customer',
            new_name='reviewer',
        ),
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='review_images'),
        ),
        migrations.AddField(
            model_name='review',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 23, 8, 11, 229535, tzinfo=datetime.timezone.utc)),
        ),
    ]
