# Generated by Django 5.0.4 on 2024-04-25 09:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0017_rename_barber_review_recipient_barber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='response',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 21, 27, 29, 813961, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviewreply_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.barber')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reserve.review')),
            ],
        ),
    ]
