# Generated by Django 3.2.23 on 2024-04-25 11:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0018_remove_review_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='reserve.salon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='reserve.barber'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='reserve.customer'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 23, 49, 39, 880922, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.customer')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='reservations',
            field=models.ManyToManyField(blank=True, related_name='appointments', to='reserve.Reservation'),
        ),
    ]
