# Generated by Django 5.0.4 on 2024-04-25 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0018_remove_review_response_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='ResponseMessage',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 22, 59, 32, 41387, tzinfo=datetime.timezone.utc)),
        ),
    ]
