# Generated by Django 3.2.23 on 2024-04-25 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0019_auto_20240425_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 23, 53, 0, 483983, tzinfo=utc)),
        ),
    ]
