# Generated by Django 5.0.4 on 2024-04-30 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0019_rename_response_responsemessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 3, 7, 38, 51150, tzinfo=datetime.timezone.utc)),
        ),
    ]
