# Generated by Django 5.0.4 on 2024-05-06 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0020_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingGifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif_name', models.CharField(max_length=255)),
                ('gif_json', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='landingup',
            old_name='description',
            new_name='hero_section_description',
        ),
        migrations.RenameField(
            model_name='landingup',
            old_name='title',
            new_name='hero_section_title',
        ),
        migrations.RemoveField(
            model_name='landingup',
            name='gif_url',
        ),
        migrations.RemoveField(
            model_name='landingup',
            name='landing_image',
        ),
        migrations.AddField(
            model_name='landingup',
            name='hero_section_image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='landingup',
            name='hero_section_image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 0, 27, 40, 456721, tzinfo=datetime.timezone.utc)),
        ),
    ]
