# Generated by Django 5.0.4 on 2024-05-08 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0021_landinggifs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 0, 22, 50, 175740, tzinfo=datetime.timezone.utc)),
        ),
    ]
