# Generated by Django 3.2.23 on 2024-04-25 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0022_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='services_offered',
            field=models.ManyToManyField(blank=True, to='reserve.Service'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 23, 57, 7, 473092, tzinfo=utc)),
        ),
    ]
