# Generated by Django 3.2.23 on 2024-04-25 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0023_auto_20240425_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='salons',
            field=models.ManyToManyField(related_name='barbers', to='reserve.Salon'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='services_offered',
            field=models.ManyToManyField(to='reserve.Service'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 23, 57, 37, 891831, tzinfo=utc)),
        ),
    ]
