# Generated by Django 5.0.4 on 2024-05-15 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0023_alter_passwordreset_expires_at_chat_message_gptcall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='text_embedding',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text_translation',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 23, 31, 42, 803263, tzinfo=datetime.timezone.utc)),
        ),
    ]
