# Generated by Django 5.0.4 on 2024-05-15 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0024_remove_message_text_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 0, 7, 18, 447575, tzinfo=datetime.timezone.utc)),
        ),
    ]
