# Generated by Django 5.0.4 on 2024-05-15 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0025_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='barber',
            field=models.ManyToManyField(blank=True, null=True, to='reserve.barber'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 0, 56, 58, 649677, tzinfo=datetime.timezone.utc)),
        ),
    ]
