# Generated by Django 5.0.4 on 2024-05-15 13:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0026_salon_barber_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='salons',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 1, 22, 11, 869016, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='barber',
            name='salons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='reserve.salon'),
        ),
    ]
