# Generated by Django 5.0.4 on 2024-05-15 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0027_remove_barber_salons_alter_passwordreset_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 1, 48, 29, 929564, tzinfo=datetime.timezone.utc)),
        ),
    ]
