# Generated by Django 3.2.23 on 2024-04-25 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0028_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 0, 4, 40, 572606, tzinfo=utc)),
        ),
    ]
