# Generated by Django 5.0.4 on 2024-05-15 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0028_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='salon',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 1, 54, 41, 394946, tzinfo=datetime.timezone.utc)),
        ),
    ]
