# Generated by Django 3.2.23 on 2024-05-18 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0029_remove_review_salon_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='barber',
            name='services_offered',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='reserve.Service'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 22, 52, 10, 845684, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salon',
            name='barber',
            field=models.ManyToManyField(blank=True, null=True, related_name='salon', to='reserve.Barber'),
        ),
        migrations.CreateModel(
            name='BlockedTimesOfBarber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.barber')),
            ],
        ),
    ]
