# Generated by Django 5.0.4 on 2024-05-15 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0029_remove_review_salon_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 2, 58, 19, 96642, tzinfo=datetime.timezone.utc)),
        ),
    ]
