# Generated by Django 3.2.23 on 2024-04-25 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0031_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='salons',
            field=models.ManyToManyField(blank=True, related_name='barbers', to='reserve.Salon'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='services_offered',
            field=models.ManyToManyField(blank=True, to='reserve.Service'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 1, 12, 46, 602375, tzinfo=utc)),
        ),
    ]
