# Generated by Django 3.2.23 on 2024-05-18 11:44

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0032_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 23, 44, 35, 278277, tzinfo=utc)),
        ),
    ]
