# Generated by Django 3.2.23 on 2024-04-25 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0032_auto_20240425_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 1, 17, 50, 556291, tzinfo=utc)),
        ),
    ]
