# Generated by Django 3.2.23 on 2024-05-04 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0033_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 2, 44, 24, 197019, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='WorkTimeModelForBarber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('work_start_time', models.TimeField()),
                ('work_end_time', models.TimeField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_times', to='reserve.barber')),
            ],
            options={
                'unique_together': {('barber', 'day_of_week')},
            },
        ),
        migrations.AddField(
            model_name='barber',
            name='WorkTimeForEachBarber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='reserve.worktimemodelforbarber'),
        ),
    ]
