# Generated by Django 5.0.4 on 2024-05-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0030_alter_passwordreset_expires_at'),
        ('reserve', '0033_alter_passwordreset_expires_at'),
    ]

    operations = [
    ]
