# Generated by Django 5.0.4 on 2024-05-22 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0034_merge_20240521_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='salons',
            new_name='salon',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='barber',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 7, 11, 49, 867097, tzinfo=datetime.timezone.utc)),
        ),
    ]
