# Generated by Django 3.2.23 on 2024-05-04 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0034_auto_20240504_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reservations',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 8, 51, 59, 568505, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
