# Generated by Django 3.2.23 on 2024-05-22 20:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0034_merge_20240521_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 8, 14, 40, 243519, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='reserve.customer')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='reserve.appointment')),
            ],
        ),
    ]
