# Generated by Django 3.2.23 on 2024-05-22 21:00

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0035_auto_20240522_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 9, 0, 17, 28022, tzinfo=utc)),
        ),
    ]
