# Generated by Django 3.2.23 on 2024-05-04 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0035_auto_20240505_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 9, 9, 0, 101202, tzinfo=utc)),
        ),
    ]
