# Generated by Django 3.2.23 on 2024-05-22 21:19

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0036_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 9, 19, 52, 983417, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
