# Generated by Django 5.0.4 on 2024-05-22 19:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0036_rename_salon_barber_salons_salon_barber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='salons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbers', to='reserve.salon'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 7, 58, 30, 360265, tzinfo=datetime.timezone.utc)),
        ),
    ]
