# Generated by Django 3.2.23 on 2024-05-04 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0036_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 9, 21, 23, 278118, tzinfo=utc)),
        ),
    ]
