# Generated by Django 3.2.23 on 2024-05-04 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0037_auto_20240505_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTimesOfBarber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='WorkTimeForEachBarber',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 9, 53, 8, 231091, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='WorkTimeModelForBarber',
        ),
        migrations.AddField(
            model_name='blockedtimesofbarber',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.barber'),
        ),
    ]
