# Generated by Django 5.0.4 on 2024-05-23 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0037_alter_barber_salons_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='salon',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 5, 24, 4, 225644, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('HC', 'Haircut'), ('SH', 'Shave'), ('TR', 'Trim')], max_length=2),
        ),
    ]
