# Generated by Django 5.0.4 on 2024-05-23 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0038_remove_gallery_salon_alter_passwordreset_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='salons',
            new_name='salon',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='barber',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 6, 10, 26, 32964, tzinfo=datetime.timezone.utc)),
        ),
    ]
