# Generated by Django 5.0.4 on 2024-05-23 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0039_rename_salons_barber_salon_remove_salon_barber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='salon',
            new_name='salons',
        ),
        migrations.AddField(
            model_name='salon',
            name='barber',
            field=models.ManyToManyField(blank=True, null=True, related_name='salon', to='reserve.barber'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 6, 11, 57, 76392, tzinfo=datetime.timezone.utc)),
        ),
    ]
