# Generated by Django 5.0.4 on 2024-05-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0037_auto_20240523_0049'),
        ('reserve', '0040_rename_salon_barber_salons_salon_barber_and_more'),
    ]

    operations = [
    ]
