# Generated by Django 5.0.4 on 2024-05-23 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0041_merge_20240523_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 6, 52, 35, 350085, tzinfo=datetime.timezone.utc)),
        ),
    ]
