# Generated by Django 5.0.4 on 2024-05-23 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0042_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 7, 17, 0, 801792, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='salon',
            name='phone_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('HC', 'Haircut'), ('SH', 'Shave'), ('TR', 'Trim')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
