# Generated by Django 5.0.4 on 2024-05-29 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0044_alter_passwordreset_expires_at_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 22, 39, 48, 465873, tzinfo=datetime.timezone.utc)),
        ),
    ]
