# Generated by Django 5.0.4 on 2024-05-29 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0045_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 23, 13, 22, 828268, tzinfo=datetime.timezone.utc)),
        ),
    ]
