# Generated by Django 5.0.4 on 2024-05-29 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0046_remove_gallery_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 23, 28, 47, 104855, tzinfo=datetime.timezone.utc)),
        ),
    ]
