# Generated by Django 5.0.4 on 2024-06-03 13:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0048_appointment_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='appointment',
            name='barber_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 1, 41, 41, 733216, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Customer_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointments', models.ManyToManyField(related_name='cart', to='reserve.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='reserve.customer')),
            ],
        ),
    ]
