# Generated by Django 5.0.4 on 2024-06-03 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0049_remove_appointment_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='barber_status',
            field=models.IntegerField(choices=[(-1, 'Rejected'), (0, 'Stall'), (1, 'Confirmed')], default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_status',
            field=models.IntegerField(choices=[(-1, 'Rejected'), (0, 'Stall'), (1, 'Confirmed')], default=0),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 1, 55, 59, 474180, tzinfo=datetime.timezone.utc)),
        ),
    ]
