# Generated by Django 5.0.4 on 2024-06-03 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0050_alter_appointment_barber_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 3, 30, 25, 39019, tzinfo=datetime.timezone.utc)),
        ),
    ]
