# Generated by Django 3.2.23 on 2024-06-04 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0051_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 4, 50, 55, 68464, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.barber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.customer')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.salon')),
            ],
        ),
    ]
