# Generated by Django 3.2.23 on 2024-06-04 16:53

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0052_auto_20240604_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 4, 53, 2, 611611, tzinfo=utc)),
        ),
    ]
