# Generated by Django 3.2.23 on 2024-06-04 16:54

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0053_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 4, 54, 32, 558260, tzinfo=utc)),
        ),
    ]
