# Generated by Django 3.2.23 on 2024-06-04 16:55

import datetime
from django.db import migrations, models
from pytz import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0054_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 4, 55, 34, 188756, tzinfo=utc)),
        ),
    ]
