# Generated by Django 5.0.4 on 2024-06-07 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0057_alter_passwordreset_expires_at_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 1, 58, 55, 471234, tzinfo=datetime.timezone.utc)),
        ),
    ]
