# Generated by Django 5.0.4 on 2024-06-09 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0058_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 2, 5, 12, 57648, tzinfo=datetime.timezone.utc)),
        ),
    ]
