# Generated by Django 5.0.4 on 2024-07-04 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0059_barber_average_rating_alter_passwordreset_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='end_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='start_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 22, 1, 12, 873101, tzinfo=datetime.timezone.utc)),
        ),
    ]
