# Generated by Django 5.0.4 on 2024-07-04 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0060_barber_end_hour_barber_start_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 23, 29, 8, 10409, tzinfo=datetime.timezone.utc)),
        ),
    ]
