from django.contrib import admin
from .models import *

admin.site.register(PasswordReset)
admin.site.register(Barber)
admin.site.register(Customer)
admin.site.register(Salon)
admin.site.register(Service)
admin.site.register(Appointment)
admin.site.register(Review)
admin.site.register(Gallery)
admin.site.register(LandingUP)
admin.site.register(LandingMid)
admin.site.register(LandingDown)
admin.site.register(LandingGifs)
admin.site.register(ResponseMessage)
admin.site.register(Chat)
admin.site.register(Message)
admin.site.register(GPTCall)
admin.site.register(BlockedTimesOfBarber)
admin.site.register(Notification)
admin.site.register(Customer_cart)
admin.site.register(Bookmark)
admin.site.register(Request)

